In [1]:
import numpy as np  
arr1 = np.arange(4, dtype = np.float_).reshape(2, 2) 
print(arr1) 
arr2 = np.array([12, 12]) 
print(arr2) 
print(np.add(arr1, arr2)) 
print(np.subtract(arr1, arr2)) 
print(np.multiply(arr1, arr2)) 
print(np.divide(arr1, arr2)) 

arr = np.array([25, 1.33, 1, 1, 100]) 
print(np.reciprocal(arr)) 
arr2 = np.array([25], dtype = int) 
print(arr2) 
print(np.reciprocal(arr2)) 

arr = np.array([5, 10, 15]) 
print(np.power(arr, 2)) 
arr1 = np.array([1, 2, 3]) 
print(arr1) 
print(np.power(arr, arr1)) 
arr = np.array([5, 15, 20]) 
arr1 = np.array([2, 5, 9]) 
print('\nApplying mod() function:') 
print(np.mod(arr, arr1)) 
print(np.remainder(arr, arr1)) 

[[0. 1.]
 [2. 3.]]
[12 12]
[[12. 13.]
 [14. 15.]]
[[-12. -11.]
 [-10.  -9.]]
[[ 0. 12.]
 [24. 36.]]
[[0.         0.08333333]
 [0.16666667 0.25      ]]
[0.04      0.7518797 1.        1.        0.01     ]
[25]
[0]
[ 25 100 225]
[1 2 3]
[   5  100 3375]

Applying mod() function:
[1 0 2]
[1 0 2]


In [2]:
import numpy as np
a = np.array( [[1,2,3,4],[5,6,7,8]] )
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

<class 'numpy.ndarray'>
2
(2, 4)
8
int64


In [6]:
Array1 = np.array([[1 ,2, 3], [4, 5, 6], [7, 8, 9]]) 
print(Array1[:,2:3])

[[3]
 [6]
 [9]]


In [8]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
print(a[::2,1::2])

[[ 2  4]
 [10 12]
 [18 20]]


In [9]:
from numpy import *
a=array([[34,43,73],[82,22,12],[53,94,66]])
print(a.max(axis=0))
print(a.min(axis=1))

[82 94 73]
[34 12 53]
