In [2]:
import numpy as np

a = np.array( [[1,2,3],[4,5,6]] )
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

ar = np.array( [[1,2,3,4],[5,2,4,2],[1,2,0,1]])
print(ar.reshape(2,2,3))
print(ar.flatten())

tmp = ar[:2,::2]
print(tmp)

cond = ar>2
print(ar[cond])

<class 'numpy.ndarray'>
2
(2, 3)
6
int64
[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]
[1 2 3 4 5 2 4 2 1 2 0 1]
[[1 3]
 [5 4]]
[3 4 5 4]


In [3]:
import numpy as np

a = np.array([1,2,5,3])
print(a+1)
print(a**2)
a *= 2
print(a)

[2 3 6 4]
[ 1  4 25  9]
[ 2  4 10  6]


In [4]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.T)
print(a.max(axis=1)) #row
print(a.min(axis=0)) #column
print(a.sum())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[3 6 9]
[1 2 3]
45


In [5]:
import numpy as np
a = np.array([[1,4,2],[3,4,6],[0,-1,5]])
print(np.sort(a,axis=None))
print(np.sort(a,axis=0,kind='mergesort'))

[-1  0  1  2  3  4  4  5  6]
[[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [6]:
import numpy as np

dtypes = [('name','S10'),('year','int'),('cgpa','float')]
values = [('dishen',2018,9.31),('darshan',2019,8.95),('dhruv',2017,9.01),('sharwil',2018,8.78)]
a = np.array(values,dtype=dtypes)
print(np.sort(a,order='name'))
print(np.sort(a,order=['cgpa','year']))

[(b'darshan', 2019, 8.95) (b'dhruv', 2017, 9.01) (b'dishen', 2018, 9.31)
 (b'sharwil', 2018, 8.78)]
[(b'sharwil', 2018, 8.78) (b'darshan', 2019, 8.95) (b'dhruv', 2017, 9.01)
 (b'dishen', 2018, 9.31)]


In [7]:
from numpy import *

a = array([12,3,45,6],int)
print(a)
print(a.dtype)
a = array([1,2,3,4.8,5.2]) #automatically get data type of array
print(a)

[12  3 45  6]
int64
[1.  2.  3.  4.8 5.2]


In [8]:
from numpy import *
a = linspace(0,15,16) #1.start 2.end 3.partition
print(a)
a = arange(0,15,2) #1.start 2.end 3.step of skip
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[ 0  2  4  6  8 10 12 14]


In [9]:
from numpy import *
a = array([1,2,3,4])
b = a
print(id(a)) # both are pointing to same array
print(id(b)) # ^
b = a.view() # create array at diff position (shallow copy)
print(id(a))
print(id(b))
b = a.copy() # deep copy
print(id(a))
print(id(b))


139709447449296
139709447449296
139709447449296
139709447449856
139709447449296
139709447450256


In [10]:
def person(name,**data):
  print(name)
  #print(data)
  for i,j in data.items():
    print(i,j)
    
person('dishen',age=21,city='Rajkot',mob=8758586868)

dishen
age 21
city Rajkot
mob 8758586868


In [12]:
from functools import reduce
n = [3,2,4,7,8,9,1]
evens = filter(lambda n:n%2==0,n)
doubles = map(lambda n:n*n,evens)
sum = reduce(lambda a,b:a+b, doubles)
print(doubles)
print(sum)


84
